version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "optimized-singlethreaded"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lcijqelr5irz"
s3_prefix = "optimized-singlethreaded"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

