version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-http-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lcijqelr5irz"
s3_prefix = "aws-http-api"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"

