AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: True

Resources:
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: does.not::matter
      Runtime: provided
      CodeUri: target/function.zip
      MemorySize: 2048
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
        - S3CrudPolicy:
            BucketName: '*'
      Timeout: 30
      Tracing: Active
      Events:
        PetResource:
          Type: Api
          Properties:
            Path: /pet
            Method: post

Outputs:
  GraalVMNativeImageLambdaClinicServiceURL:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
